@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.rainbowfountain.content;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;